name: Dusk

on: [pull_request, push]

jobs:
  dusk:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.2'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Upgrade Chrome Driver
        run: php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux
      - name: Run Laravel Server
        run: php artisan serve --no-reload &
      - name: Run Dusk Test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          APP_URL: "http://127.0.0.1:8000"
        run: php artisan dusk
